### PR TITLE
Load models from explicit files

### PR DESCRIPTION
**Pull request by heuristicus**
These changes allow loading of models from `.sta`, `.tra` and the other explicit files that can be generated from a model using the `-exportmodel .all` command of PRISM.

For example, loading a ~70k state flat MDP takes approximately 300 seconds from the `to_prism_string` output. Converting the model to explicit files (which currently takes 300 seconds) and loading it using these changes takes 0.2 seconds.

I'm adding this because currently flat MDPs are extremely inefficient to load into PRISM because it has to do reachability on the model despite all states being enumerated already in the file. The `-exportmodel .all` command also does reachability if given the full prism model spec, so it's not possible to bypass reachability to generate the explicit files at the moment. PR to follow in other repos which allows conversion of flat MDP to the explicit files directly.

To do this I've had to make a slight change to how commands are passed to the rapport talker. The first line passed to the talker, which used to contain just the command like `plan`, `check`, etc, can  now look something like `plan explicit_model`. You can pass in space-separated strings as something like configuration arguments to the command. I did it this way because putting the explicit model flag on a new line would have required conditionally parsing it for each individual command, which would have been extremely messy.

There is currently an issue where the transition rewards are apparently not loaded. Have asked Dave for input on why it might not be working.

Here's a small example which can be used for testing

[tmp_model_small.zip](https://github.com/user-attachments/files/16411677/tmp_model_small.zip)

Use this python script

```
import shutil
import os
from rapport_external.prism_bridge import create_bridge

if __name__ == "__main__":
    model_dir = "tmp_model_small"
    model_name = "product_mdp"
    explicit_file_fstrings = ["{}.sta", "{}.tra", "{}.lab", "{}.srew", "{}.trew"]
    explicit_files = [fstr.format(model_name) for fstr in explicit_file_fstrings]
    model_file = os.path.join(model_dir, f"{model_name}.prism")
    model_id = "test_model"
    with open(model_file, "r") as f:
        model_string = f.read()

    with create_bridge(remove_dir=False, explicit_model=True) as bridge:
        bridge.add_model(model_id, model_string)
        bridge.configure_prism("prism.engine", "Hybrid")
        for exp_file_fstr in explicit_file_fstrings:
            shutil.copyfile(
                os.path.join(model_dir, exp_file_fstr.format(model_name)),
                os.path.join(bridge._work_dir, exp_file_fstr.format(model_id + "_model")),
            )

        bridge.call_prism_plan(model_id, "Rmax=? [ C ]")

```

### CODE REVIEW

**Comment by bfalacerda** [comment]
for your example, how long does it take to write the files from the flatMDP?

**Comment by heuristicus** [comment]
I haven't implemented that bit yet.

**Comment by heuristicus** [comment]
Update: I more or less completed the flat mdp to explicit file conversion, and it takes ~5 seconds to export the model with ~70k states, as opposed to the ~300 seconds needed to load it from the standard prism file. Loading the explicit files is also extremely fast.

Actually might not be 5 seconds, was working through a bug.

**Comment by heuristicus** [comment]
There seems to be an issue where prism complains about the labels not being correctly loaded. Here I'm running prism directly with the files from the zip file:

```
michal@vimes ~/Documents/code/git/reactive-mdp/scripts $ ~/Documents/code/git/prism/prism/bin/prism ./tmp_model_small/product_mdp.all -pf 'Pmax=? [ F "accepting" ]'
PRISM
=====

Version: 4.8.1.dev
Date: Fri Sep 06 16:31:12 BST 2024
Hostname: vimes
Memory limits: cudd=1g, java(heap)=1g
Command line: prism ./tmp_model_small/product_mdp.all -pf 'Pmax=? [ F "accepting" ]'

Warning: Import of transition rewards is not yet supported so ./tmp_model_small/product_mdp.trew is being ignored

Importing model from "./tmp_model_small/product_mdp.tra", "./tmp_model_small/product_mdp.sta", "./tmp_model_small/product_mdp.lab", "./tmp_model_small/product_mdp.srew"...
Auto-detected model type: MDP
Checking module labels
Checking label "accepting"

1 property:
(1) Pmax=? [ F "accepting" ]

---------------------------------------------------------------------

Model checking: Pmax=? [ F "accepting" ]

Building model...

Computing reachable states...

Reachability (BFS): 12 iterations in 0.01 seconds (average 0.000833, setup 0.00)

Time for model construction: 0.165 seconds.

Type:        MDP
States:      855 (1 initial)
Transitions: 2545
Choices:     2418

Transition matrix: 13525 nodes (4 terminal), 2545 minterms, vars: 32r/32c/5nd

Prob0A: 9 iterations in 0.01 seconds (average 0.001111, setup 0.00)

Prob1E: 4 iterations in 0.02 seconds (average 0.005000, setup 0.00)

yes = 6, no = 828, maybe = 21

Computing remaining probabilities...
Engine: Hybrid

Building hybrid MTBDD matrices... [nm=4, levels=32, nodes=3120] [146.2 KB]
Adding sparse bits... [levels=32-32, num=4, compact=4/4] [3.7 KB]
Creating vector for yes... [dist=2, compact] [1.7 KB]
Allocating iteration vectors... [3 x 6.7 KB]
TOTAL: [171.7 KB]

Starting iterations...

Iterative method: 9 iterations in 0.00 seconds (average 0.000000, setup 0.00)

Value in the initial state: 0.7290000000000001

Time for model checking: 0.014 seconds.

Result: 0.7290000000000001 (exact floating point)

---------------------------------------------------------------------

Note: There was 1 warning during computation.
```

I would expect that loading the same model files in through the prism bridge should thus give the same output, but it does not:

```
michal@vimes ~/Documents/code/git/reactive-mdp/scripts $ python3 explicit_test.py 
PRISM server running on port 58484
PRISM
=====

Version: 4.8.1.dev
Date: Fri Sep 06 16:33:36 BST 2024
Hostname: vimes
Memory limits: cudd=1g, java(heap)=4g
got connection on port58484
received: configure
Set prism.engine to Hybrid
received: plan explicit_model
loading prism model file
Loading model from explicit files.
Auto-detected model type: MDP

Building model...

Computing reachable states...

Reachability (BFS): 12 iterations in 0.01 seconds (average 0.000833, setup 0.00)

Time for model construction: 0.192 seconds.

Type:        MDP
States:      855 (1 initial)
Transitions: 2545
Choices:     2418

Transition matrix: 13525 nodes (4 terminal), 2545 minterms, vars: 32r/32c/5nd

Exporting list of reachable states in plain text format to file "/home/michal/Documents/code/git/reactive-mdp/scripts/prism_tmp_58484/test_model_original.sta"...
Checking module labels
Checking label "accepting"
Error: Undeclared label (""accepting"", line 1, column 10)
received: shutdown

```

Somehow, the label is not being correctly imported, and I'm not sure why.

**Comment by davexparker** [comment]
Which API functions are called to load/check the property? For me, this similar code at the Java level works fine, for either `master` or `robots`:

```
PrismLog mainLog = new PrismFileLog("stdout");
Prism prism = new Prism(mainLog);
prism.initialise();
prism.loadModelFromExplicitFiles(
		new File("/Users/dxp/prism/prism/prism-tests/functionality/import/dice.sta"),
		new File("/Users/dxp/prism/prism/prism-tests/functionality/import/dice.tra"),
		new File("/Users/dxp/prism/prism/prism-tests/functionality/import/dice.lab"),
		null,
		null
);
prism.modelCheck("P=?[F \"six\"]");
```

**Comment by heuristicus** [comment]
From what I can tell, that seems to be more or less the process which we're using in the `PrismRapportTalker` to do things, but I ran my little test script through with the dice example and get the same error, that the "six" label is missing.

We first parse the command we send, in this case it's a plan command, so we enter at

https://github.com/ori-goals/prism/blob/e018a8c511dbeb4aef4aec8a6a609d1c9acf77ac/prism/src/prism/PrismRapportTalker.java#L542

We then load the model at

https://github.com/ori-goals/prism/blob/e018a8c511dbeb4aef4aec8a6a609d1c9acf77ac/prism/src/prism/PrismRapportTalker.java#L120-L148

which calls the `loadModelFromExplicitFiles` function of prism.

After than, we run this code. The command I've been sending for my work is `Pmax=? [ F "accepting" ]`, in the dice case `P=? [ F "six" ]`.


https://github.com/ori-goals/prism/blob/e018a8c511dbeb4aef4aec8a6a609d1c9acf77ac/prism/src/prism/PrismRapportTalker.java#L242-L261

I did a bit more fiddling, and it seems like the crash comes from the `prism.parsePropertiesString(currentModel, propString)`. If I skip this part of the code and just use the `propString` to pass to `checkModel` I can get the model output correctly. As you can see we're using the properties string parsing to get some information about the spec to do some stuff with the outputs. Can you suggest an alternative way of doing this so we can avoid this crash?

**Comment by davexparker** [comment]
Can you try using `prism.parsePropertiesString(propString)` instead of `prism.parsePropertiesString(currentModel, propString)`, which is preferred and guarantees that the property is parsed against the model currently loaded into PRISM?

**Comment by heuristicus** [comment]
Tested and works with the explicit model loading and also the standard model loading we usually do. Also ran all the rapport tests which use the prism bridge, and they all pass, so looks like that fixes it. Thank you!

**Comment by davexparker** [comment]
Great! That API method was already deprecated for this reason, and in later branches is actually now removed I think.

**Pull request merged**
